version: '3.8'

services:
  todo-backend:
    build: ./rust
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info

  todo-scala:
    build: ./scala
    ports:
      - "8001:8080"
    environment:
      - PORT=8080

  todo-java:
    build: ./java
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker